### ISSUE TITLE
您好 我重新装了一个树莓派 

### ISSUE THREAD

**Issue by hero37th** [EAIBOT/dashgo#5]
ubuntu系统16.04+kinetic+dashgo D1

warehouse_ros 和world_canvas_server好像出了问题，请问我有什么解决的方法吗？
此外rviz构建出的地图会旋转
![image](https://user-images.githubusercontent.com/49057215/79103617-856ce600-7d9f-11ea-8b8d-8b87bda303c8.png)
![image](https://user-images.githubusercontent.com/49057215/79103648-90c01180-7d9f-11ea-9566-00b8c95cb0fa.png)
![image](https://user-images.githubusercontent.com/49057215/79103661-9ae21000-7d9f-11ea-8a37-4fba9d797eac.png)

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/world_canvas_server/world_canvas_server", line 6, in <module>
    import world_canvas_server
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/world_canvas_server/__init__.py", line 1, in <module>
    from .annotations_server import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/world_canvas_server/annotations_server.py", line 40, in <module>
    import warehouse_ros as wr
ImportError: No module named warehouse_ros
[world_canvas_server-11] process has died [pid 10574, exit code 1, cmd /opt/ros/kinetic/lib/world_canvas_server/world_canvas_server false __name:=world_canvas_server __log:=/home/robotlab/.ros/log/2e298f78-d0e3-11e5-aebe-b827ebe23586/world_canvas_server-11.log].
log file: /home/robotlab/.ros/log/2e298f78-d0e3-11e5-aebe-b827ebe23586/world_canvas_server-11*.log

**Comment by hero37th** [comment]
或者您重新发给我一份可以用的安装包？我重新安装一下 Raspberry_pi
